//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Betotrans.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aggregate
    {
        public int AggregateId { get; set; }
        public string AggregateName { get; set; }
        public string AggregateTitle { get; set; }
        public string ImgUrl { get; set; }
        public string MiniImgUrl { get; set; }
        public string Size { get; set; }
        public string IntendedFor { get; set; }
        public string Description { get; set; }
    }
}
